package puzzle.edge;

import java.awt.Point;
import java.awt.Shape;
import java.util.Random;

import puzzle.storeage.JigsawPuzzleException;

/**
 * interface for all producers of edges. The way they go is first call
 * contructor to contruct new object, than init the object with some parameters
 * that are predefined and wouldn't be changed in the process, later call
 * produce as often as you need to produce several edges that suit to your
 * predefinitions made trough the init method. At last call the getShapes method
 * this method will give you the produces edges as a contrary pair
 * 
 * @author Heinz
 * 
 */
/**
 * interface para todos os produtores de bordas. O jeito que eles vão é a primeira chamada
 * construtor para construir um novo objeto, do que inicializar o objeto com alguns parâmetros
 * que são predefinidos e não seriam alterados no processo, chame posteriormente
 * produza com a freqüência necessária para produzir várias arestas que se adaptem ao seu
 * predefinições feitas através do método init. Por fim, chame o método getShapes
 * este método fornecerá as arestas produzidas como um par contrário
 * 
 * @autor Heinz
 * 
 */

public abstract class AbstractEdgeProducer {
	
	/**
	 * a random number generator - the key thing for production
	 */
	/**
	 * um gerador de números aleatórios - a chave para a produção
	 */
	protected static final Random rand = new Random();
	
	/**
	 * the points for the actual shape
	 */
	/**
	 * os pontos para a forma real
	 */
	protected Point[] actualPoints;

	/**
	 * if this is a male one = true, otherwise if female on = false
	 */
	/**
	 * se for masculino = verdadeiro, caso contrário, se for feminino = falso
	 */
	protected boolean isBubble;

	/**
	 * the two generated shapes are saved here
	 */
	/**
	 * as duas formas geradas são salvas aqui
	 */
	protected Shape[] twoShapes;
	
	/**
	 * length of a side
	 */
	/**
	 * comprimento de um lado
	 */
	protected int sideLength;

	/**
	 * this should init this produces with the predifined side length
	 */
	/**
	 * isto deve iniciar e produzir com o comprimento de lado predefinido
	 */
	public void init(int sideLength) {
		this.sideLength = sideLength;
		this.isBubble = rand.nextBoolean();
		_init();
	}
	
	/**
	 * delegation of init method if additional initiation stuff has to be done
	 */
	/**
	 * delegação do método init se algo de iniciação adicional tiver que ser feito
	 */
	protected abstract void _init();

	/**
	 * this should produce a random edge, might be called as often as needed to
	 * produce new edges from given type (type given by init)
	 * 
	 */
	/**
	 * isso deve produzir uma borda aleatória, pode ser chamado tão frequentemente quanto necessário para
	 * produz novas arestas de determinado tipo (tipo fornecido por init)
	 * 
	 */
	public abstract void produce() throws JigsawPuzzleException;

	/**
	 * retrieves the two shapes generated by this producer through the produce
	 * procedure, no special order the first might be a male or female type
	 * 
	 * @return a two fielded array containing the shapes
	 */
	/**
	 * recupera as duas formas geradas por este produtor por meio do produto
	 * procedimento, nenhum pedido especial o primeiro pode ser um tipo masculino ou feminino
	 * 
	 * @return um array de dois campos contendo as formas
	 */
	public Shape[] getBothShapes() {
		return this.twoShapes;
	}
	
	/**
	 * this method recalculates the points of the actualPoints list
	 * to get a female piece.
	 */
	/**
	 * este método recalcula os pontos da lista de pontos reais
	 * para obter uma peça feminina.
	 */
	protected void recalculate() {
		if (!this.isBubble) {
			// turnsTheActualPoint Ys -> to get the female
			for (Point p : this.actualPoints) {
				p.y *= -1;
			}
		}
	}

}
